# Generated by Django 6.0.4 on 2026-05-28 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country', models.CharField(choices=[('PA', 'Panama'), ('CR', 'Costa Rica'), ('CO', 'Colombia'), ('MX', 'Mexico'), ('US', 'United States'), ('OT', 'Other')], default='PA', max_length=2)),
                ('city', models.CharField(default='Panama City', max_length=100)),
                ('currency', models.CharField(default='PAB', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_tenant',
            },
        ),
        migrations.CreateModel(
            name='StorefrontSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('tagline', models.TextField(blank=True, default='')),
                ('primary_phone', models.CharField(blank=True, default='', max_length=50)),
                ('whatsapp_phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_storefront_enabled', models.BooleanField(default=False)),
                ('responsible_drinking_message', models.TextField(blank=True, default='Please drink responsibly. Must be of legal drinking age in your jurisdiction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_storefront_settings',
            },
        ),
        migrations.CreateModel(
            name='OperatingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('accepts_orders', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_schedules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_operating_schedule',
                'ordering': ['weekday'],
            },
        ),
    ]
