# Generated by Django 6.0.4 on 2026-05-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FAILED_AGE_VERIFICATION', 'Failed Age Verification'), ('DELIVERY_REFUSED', 'Delivery Refused'), ('RECEIVER_UNAVAILABLE', 'Receiver Unavailable'), ('VISIBLY_INTOXICATED', 'Visibly Intoxicated'), ('UNATTENDED_DELIVERY_ATTEMPT', 'Unattended Delivery Attempt'), ('HANDED_TO_MINOR', 'Handed to Minor'), ('ADMIN_REJECTION', 'Admin Rejection'), ('OTHER', 'Other')], max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='orders.order')),
            ],
            options={
                'db_table': 'compliance_complianceevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(blank=True, default='', max_length=200)),
                ('receiver_document_checked', models.BooleanField(default=False)),
                ('receiver_is_adult', models.BooleanField(blank=True, default=None, null=True)),
                ('verified_by', models.CharField(blank=True, default='', max_length=200)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_verifications', to='orders.order')),
            ],
            options={
                'db_table': 'compliance_deliveryverification',
                'ordering': ['-delivered_at'],
            },
        ),
    ]
